### PR TITLE
WIP: Remove need for copying the core src into consumer repo

### PR DESCRIPTION
**Pull request by jtfell**
Following on from this PR: https://github.com/jawj/zapatos/pull/26

I've tried this branch (heavily inspired by the effort by @eyelidlessness, just updated based on the latest state of master) on my closed source project that uses `ts-jest` and `ts-node-dev` and had no problems with the generated schema being found.

I'd be interested if you are able to reproduce your issue in the open so we can figure out what is going on @jawj. I'm conscious of taking up too much of your time with this but I really feel that it will help adoption of this library if the configuration is less unusual.

### CODE REVIEW

**Comment by jawj** [comment]
I'm going to do some more work on this, but right now I'm a bit confused.

The old @eyelidlessness fork makes the thing work by renaming `schema.ts` to `schema.d.ts` and wrapping the whole thing in a `declare module 'zapatos/schema' { /* ... */ }` declaration.

This works fine for me in VS Code and when using plain `tsc`, but breaks down when running via either `ts-node` or `ts-jest`.

Your fork, `jtfell:refactor/no-schema-copy`, doesn't seem to use a declaration? Therefore it seems that the schema isn't found at all by the zapatos code in `node_modules` (which still tries to import it from `'zapatos/schema'`) and all the shortcuts, for example, remain effectively untyped.

Can you clarify that you have this working, in the sense of compiling _and_ inferring the correct types for calls to `select`, `insert`, and so on?

**Comment by jtfell** [comment]
Sorry, the project I was testing in had the generated schema at `src/zapatos/schema.d.ts` so it was automatically being resolved correctly. I moved the schema to `src/gen/zapatos/schema.d.ts` (ie. I set outDir to `./src/gen`), and was able to replicate that it wasn't resolved by `tsc`.

I've pushed a new commit that adds the module declarations, and it now works for me in both configurations (and with ts-jest, ts-node)

**Comment by jawj** [comment]
Thanks. OK, I've got my closed source project to the same point with this as before — i.e. `tsc` and VS Code are happy, `ts-jest` and `ts-node` are not (both with errors involving `Cannot find module 'zapatos/schema'`). Now to figure this out and/or extract a shareable test case.

**Comment by jawj** [comment]
Huh. I created a minimal test case repo using all the same configuration as my closed-source project — and it works perfectly. 

Continuing to try to get to the bottom of this ...

**Comment by jawj** [comment]
OK, I think I'm there. The required steps were:

* To avoid trouble with `ts-jest`, make sure always to `import type` the schema (e.g. `import type * as schema from 'zapatos/schema';`) .
* To avoid trouble with `ts-node` or `node -r ts-node/register`, set `TS_NODE_FILES=true` (e.g. `TS_NODE_FILES=true nodemon --watch 'src/**/*.ts' --exec 'node --inspect -r ts-node/register src/index.ts'`).
* Clean out the build folder (in my case, `lib`) before running either. This one definitely shouldn't be necessary, but definitely seemed to help with `ts-node`.

I think I consider the concept proven! Many thanks @jtfell and @eyelidlessness.

If we're going to make the switch to this way of doing things, there'll be a chunk of new documentation needed, and I also wonder if custom types are going to need any extra work ...

**Comment by jawj** [comment]
(This is my test case: https://github.com/jawj/zapatos-nocopy-testcase)

**Comment by jtfell** [comment]
Custom types are working for me as is. I only have a single PgGeometry type assigned for Postgis geometries but the types are being resolved properly

**Comment by jawj** [comment]
OK — I've done quite a bit of refactoring (including no longer using Zapatos for the schema introspection, because that caused lots of type headaches for not much benefit), and also added support for importing as an ESM module.

I've checked that it works with three of my own projects (`zapatos-demo` and `zapatos-docs` here on GitHub, and one that's closed-source and uses `ts-node` and `ts-jest`).

The current state of things is at https://github.com/jawj/zapatos/tree/no-copy

Detailed migration instructions are given when you run `npx zapatos` in the new version. These can also be found here (and will eventually find their way to the docs): https://github.com/jawj/zapatos/blob/no-copy/src/generate/legacy.ts

This will all be released as 3.0.0 at some point when I have the docs updated. If anyone on here (including you, of course, @jtfell) is able to kick the tyres first and flag up any teething problems, that would be much appreciated. You should be able to `npm install` from the GitHub branch.

**Comment by jtfell** [comment]
This looks really great @jawj - thanks for persisting with it!

I installed version 2.0.1, generated the schema, installed the new one and regenerated it. The migration message was helpful and all the steps worked until I got to custom types. It couldn't resolve my custom type at `src/zapatos/custom/PgGeometry.d.ts`, but this was fixed by creating a file at `src/zapatos/custom/index.d.ts` with the contents:

```
declare module 'zapatos/custom' {}
```

This allows the custom files to automatically extend the module without any changes to them. 

I also don't seem to need `TS_NODE_FILES=true` or `--files` with `ts-node-dev`. I'm unsure if this a config thing or a difference with `ts-node` but I'm happy about it 😄

**Comment by jawj** [comment]
> It couldn't resolve my custom type at `src/zapatos/custom/PgGeometry.d.ts`, but this was fixed by creating a file at `src/zapatos/custom/index.d.ts` with the contents:
> 
> ```
> declare module 'zapatos/custom' {}
> ```

@jtfell Hmm, that seems a bit odd. My custom types are definitely found without it. Do you think `index.d.ts` is a magic name in this context? It presumably only helps to the extent that it enables the compiler to find your custom type file when it otherwise wouldn't, and that also seems slightly unexpected.

Which is the 'it' that won't resolve the custom type: VS Code? `tsc`? `ts-node-dev`? It would be great if you could dig into this a bit more, since I don't want to generate an extra file unless we're sure it's needed.

**Comment by jtfell** [comment]
`index` is a magic name generally in node so I presume it works the same for typescript. Here's the output for `tsc` when I regenerated my `src/zapatos` folder

```
> tsc

src/zapatos/schema.d.ts:12:27 - error TS2307: Cannot find module 'zapatos/custom' or its corresponding type declarations.

12   import type * as c from 'zapatos/custom';
                             ~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by jawj** [comment]
@jtfell My turn to thank you for your persistence!

The thing is, although both `zapatos/schema` and `zapatos/custom` look like file paths, in this context they're actually not paths at all — they're just the names of the [ambient modules](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules) declared in `schema.d.ts` and the files inside `zapatos/custom`.

That ought to mean the import rules you explained above don't apply — and indeed I have three separate projects all working without a `custom.d.ts` or `custom/index.d.ts` file. But it does mean you need to ensure that the `.d.ts` files are found, which can be where the `"files"` or `"include"` keys in `tsconfig.json`, and the `--files` argument to `ts-node`, come in.

I think what would be most helpful in resolving this would be if you were willing to extract a minimal test case from your a project to a public repo, that we can then troubleshoot.

[1] At build time it works slightly differently, using the `"paths"` key in `tsconfig.json`, but that shouldn't be relevant here.

**Comment by jtfell** [comment]
I've created a [PR](https://github.com/jawj/zapatos-nocopy-testcase/pull/1) that demonstrates the issue. I was surprised by it being related to importing relative types in the custom declaration. It works if you define and declare the type entirely within the custom file

**Comment by jawj** [comment]
Brilliant — thanks. I can absolutely see the issue, and I can also see that the empty ambient declaration in `custom/index.d.ts` fixes it.

I guess that persuades me that we need to generate that `index.d.ts` file, though I'm a bit uncomfortable about it, since it seems like a 'magic' fix for an unexplained bug (the nastiest thing about which is that it only appears at import sites elsewhere).

**Comment by purge** [comment]
Super work on this (and the other PRs). I've just tested it on a fairly complicated zapatos repo and it works great. As its as monorepo i had to update the `include` on all the projects to include the path to the new zapatos types (there may be a better way) but other than that the switch instructions worked great.

**Comment by jawj** [comment]
> Super work on this (and the other PRs). I've just tested it on a fairly complicated zapatos repo and it works great. As its as monorepo i had to update the `include` on all the projects to include the path to the new zapatos types (there may be a better way) but other than that the switch instructions worked great.

@purge Thanks. Just to check, are you saying there's anything else the instructions should include, or does this (existing) item cover it?

> * Ensure all the '.d.ts' files in 'zapatos' are picked up by your TypeScript configuration (e.g. check the "files" or "include" keys in 'tsconfig.json')

**Comment by purge** [comment]
@jawj yeah that does cover it, just took me a while to realise it :)

**Pull request merged**
